# Generated by Django 5.0.6 on 2025-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
