# Generated by Django 5.0.6 on 2025-06-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_goodsreceiptnoteitem_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnoteitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_items', to='products.purchaseorderitem'),
        ),
    ]
