# Generated by Django 5.0.6 on 2025-06-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_goodsreceiptnoteitem_free_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnoteitem',
            name='cost',
        ),
    ]
