# Generated by Django 5.0.6 on 2025-06-18 03:35

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('self_delivery', models.BooleanField(default=False)),
                ('delivery_fee', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\d{10}')])),
                ('hotline', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\d{10}')])),
                ('tracking_link', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('faq_description', models.TextField()),
                ('faq_type', models.CharField(blank=True, default='global', max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification_type', models.CharField(blank=True, choices=[('order', 'Order'), ('payment', 'Payment'), ('delivery', 'Delivery'), ('promotions', 'Promotion'), ('system', 'System')], default='system', max_length=20, null=True)),
                ('notification_user_group', models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer')], default='admin', max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('action_name', models.CharField(blank=True, max_length=20, null=True)),
                ('action_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('target', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfDeliveryPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\d{10}')])),
                ('alt_contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\d{10}')])),
                ('nic', models.CharField(blank=True, max_length=14, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='Company Name', max_length=100, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('invoice_hotline', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\d{10}')])),
                ('invoice_footer_note', models.TextField(blank=True, null=True)),
                ('master_pin', models.CharField(max_length=6, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo')),
                ('retina_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/logo')),
                ('invoice_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, default='global', max_length=55, null=True)),
                ('issued_by', models.CharField(blank=True, default='Super Admin', max_length=25, null=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
        ),
    ]
