# Generated by Django 5.0.6 on 2025-06-18 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accrual_rate_store', models.DecimalField(decimal_places=4, default=0.005, max_digits=5)),
                ('accrual_rate_online', models.DecimalField(decimal_places=4, default=0.01, max_digits=5)),
                ('redemption_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('register_bonus', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('points_expiry_months', models.IntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('promotion_type', models.CharField(choices=[('flat_discount', 'Flat Discount'), ('percentage_discount', 'Percentage Discount'), ('bonus_points', 'Bonus Points')], max_length=50)),
                ('flat_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bonus_points', models.IntegerField(blank=True, null=True)),
                ('max_usage_per_customer', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='Indicates hierarchy of tiers')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_threshold', models.IntegerField()),
                ('multiplier', models.DecimalField(decimal_places=3, default=0.001, max_digits=5)),
                ('badge_image', models.JSONField(blank=True, default=dict, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiers', to='loyalty.loyaltyprogram')),
            ],
            options={
                'unique_together': {('program', 'level')},
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tier_acquired_date', models.DateField(blank=True, null=True)),
                ('total_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_points_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_points_expired', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to='accounts.customerprofile')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('min_purchase', 'Minimum Purchase')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='TierPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('promotion_type', models.CharField(choices=[('flat_discount', 'Flat Discount'), ('percentage_discount', 'Percentage Discount'), ('bonus_points', 'Bonus Points')], max_length=50)),
                ('flat_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bonus_points', models.IntegerField(blank=True, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='loyalty.loyaltytier')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Earn', 'Earn Points'), ('Redeem', 'Redeem Points'), ('Expire', 'Expired Points'), ('Adjustment', 'Manual Adjustment')], max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=3, default=0.001, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='accounts.customerprofile')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('related_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.promotion')),
                ('related_tier_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.tierperk')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit to Wallet'), ('Debit', 'Debit from Wallet')], max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.customerwallet')),
            ],
        ),
    ]
