# Generated by Django 5.0.6 on 2025-06-18 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('register_id', models.CharField(max_length=20, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('denomination_5000', models.PositiveIntegerField(default=0)),
                ('denomination_1000', models.PositiveIntegerField(default=0)),
                ('denomination_500', models.PositiveIntegerField(default=0)),
                ('denomination_100', models.PositiveIntegerField(default=0)),
                ('denomination_50', models.PositiveIntegerField(default=0)),
                ('denomination_20', models.PositiveIntegerField(default=0)),
                ('denomination_10', models.PositiveIntegerField(default=0)),
                ('denomination_5', models.PositiveIntegerField(default=0)),
                ('denomination_1', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('pin_code', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashInOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('IN', 'Cash In'), ('OUT', 'Cash Out')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_records', to='pos.cashregister')),
            ],
        ),
        migrations.CreateModel(
            name='CashRegisterShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.cashregister')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_delivery_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_coupons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_online_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_qr_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bank_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cheque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_wallet_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('report_generated_at', models.DateTimeField(auto_now_add=True)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.cashregistershift')),
            ],
        ),
        migrations.AddField(
            model_name='cashregister',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='pos.terminal'),
        ),
        migrations.CreateModel(
            name='TerminalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('printer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('printer_vendor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('printer_product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('printer_port', models.IntegerField(default=9100)),
                ('auto_print_receipts', models.BooleanField(default=True)),
                ('custom_footer_message', models.TextField(blank=True, null=True)),
                ('tablet_mode', models.BooleanField(default=True)),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.terminal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashregistershift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('cash_register', 'cashier'), name='unique_active_cash_register_cashier_shift'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('terminal',), name='unique_open_register_per_terminal'),
        ),
    ]
